apiVersion: v1
kind: Service
metadata:
  name: sqlserver-cadastro
spec:
  type: LoadBalancer
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    apps: sqlserver-cadastro
