apiVersion: v1
kind: Pod
metadata:
  name: mssqltools-revendadeveiculos-pod
  labels:
    apps: mssqltools-revendadeveiculos
spec:
  containers:
    - name: mssqltools-revendadeveiculos-container
      image: fdelima/fiap-pos-techchallenge-revendadeveiculos-scripts-database:fase2
  restartPolicy: Never
