apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-pos-tech-challenge-revendadeveiculos-api-deployment
  labels:
    apps: fiap-pos-tech-challenge-revendadeveiculos-api
spec:
  replicas: 3
  selector:
    matchLabels:
      apps: fiap-pos-tech-challenge-revendadeveiculos-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps: fiap-pos-tech-challenge-revendadeveiculos-api
    spec:
      containers:
        - name: fiap-pos-tech-challenge-revendadeveiculos-api-container
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
          image: fdelima/fiap-pos-techchallenge-revendadeveiculos-api:fase2
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api-docs/index.html
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /api-docs/index.html
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 10m              
      restartPolicy: Always