version: '3.4'
volumes:
  sql_data: {}

services:
  fiap.pos.tech.challenge.revendadeveiculos.api:
    image: fdelima/fiap-pos-techchallenge-revendadeveiculos-api:fase2
    depends_on:
      - mssqltools-revendadeveiculos
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"

  finish:
    image: alpine:latest
    depends_on:
      - sqlserver-revendadeveiculos
      - mssqltools-revendadeveiculos
      - fiap.pos.tech.challenge.revendadeveiculos.api
    command: ["sh", "-c", "sleep 25; echo 'Serviço fiap.pos.tech.challenge.revendadeveiculos.api finalizado!'; echo 'acesse http://localhost:8080/api-docs'"]

  sqlserver-revendadeveiculos:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1435:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U sa -P SqlServer2019! -Q 'SELECT NAME FROM SYS.DATABASES'"]
      interval: 10s
      retries: 20
    volumes:
      - sql_data:/var/opt/mssql
  mssqltools-revendadeveiculos:
    image: fdelima/fiap-pos-techchallenge-revendadeveiculos-scripts-database:fase2
    environment:
      INSTANCE: "sqlserver-revendadeveiculos"
      USER: "sa"
      PASSWORD: "SqlServer2019!"
    depends_on:
      - sqlserver-revendadeveiculos