name: FIAP Pos Tech Challenge Revenda de Veiculos Mssql Tools Workflow

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    name: Build FIAP Pos Tech Challenge Revenda de Veiculos Mssql Tools
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
           
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        context: ./
        file: ./Docker/DataBase/Dockerfile
        #fixo, pois, sempre que trocar as secrets necessario alterar o nome da imagem a ser gerada.
        tags: ${{ secrets.DOCKER_USERNAME }}/fiap-pos-techchallenge-revendadeveiculos-scripts-database:fase2
        push: true
          